# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_caisse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#class import
from PyQt5.QtWidgets import QTableWidgetItem
from Model.Produit import implProduit
from Model.Produit import Produit


class Ui_MainWindow(object):

    code = []
    libelle = []
    quantite = []
    prix = []
    total = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 601)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Images/logomIT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btPrix = QtWidgets.QPushButton(self.centralwidget)
        self.btPrix.setGeometry(QtCore.QRect(40, 20, 131, 81))
        self.btPrix.setObjectName("btPrix")
        self.btStock = QtWidgets.QPushButton(self.centralwidget)
        self.btStock.setGeometry(QtCore.QRect(210, 20, 131, 81))
        self.btStock.setObjectName("btStock")
        self.btCompte = QtWidgets.QPushButton(self.centralwidget)
        self.btCompte.setGeometry(QtCore.QRect(450, 20, 131, 81))
        self.btCompte.setObjectName("btCompte")
        self.btQuitter = QtWidgets.QPushButton(self.centralwidget)
        self.btQuitter.setGeometry(QtCore.QRect(620, 20, 131, 81))
        self.btQuitter.setObjectName("btQuitter")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 140, 431, 121))
        self.groupBox.setObjectName("groupBox")
        self.btAdd = QtWidgets.QPushButton(self.groupBox)
        self.btAdd.setGeometry(QtCore.QRect(310, 80, 61, 31))
        self.btAdd.setObjectName("btAdd")
        self.txCode = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txCode.setGeometry(QtCore.QRect(140, 40, 151, 31))
        self.txCode.setPlainText("")
        self.txCode.setBackgroundVisible(True)
        self.txCode.setObjectName("txCode")
        self.btCheck = QtWidgets.QPushButton(self.groupBox)
        self.btCheck.setGeometry(QtCore.QRect(310, 40, 61, 31))
        self.btCheck.setObjectName("btCheck")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label_3.setObjectName("label_3")
        self.txQuantite = QtWidgets.QSpinBox(self.groupBox)
        self.txQuantite.setGeometry(QtCore.QRect(140, 80, 151, 31))
        self.txQuantite.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.txQuantite.setObjectName("txQuantite")
        self.btCancelA = QtWidgets.QPushButton(self.groupBox)
        self.btCancelA.setGeometry(QtCore.QRect(380, 40, 31, 71))
        self.btCancelA.setObjectName("btCancelA")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(530, 140, 241, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(50, 70, 51, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 100, 61, 16))
        self.label_5.setObjectName("label_5")
        self.lbCaisse = QtWidgets.QLabel(self.groupBox_2)
        self.lbCaisse.setGeometry(QtCore.QRect(150, 40, 58, 16))
        self.lbCaisse.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCaisse.setObjectName("lbCaisse")
        self.lbCaissier = QtWidgets.QLabel(self.groupBox_2)
        self.lbCaissier.setGeometry(QtCore.QRect(110, 70, 141, 16))
        self.lbCaissier.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCaissier.setObjectName("lbCaissier")
        self.lbManager = QtWidgets.QLabel(self.groupBox_2)
        self.lbManager.setGeometry(QtCore.QRect(110, 100, 141, 16))
        self.lbManager.setAlignment(QtCore.Qt.AlignCenter)
        self.lbManager.setObjectName("lbManager")
        self.lbDate = QtWidgets.QLabel(self.groupBox_2)
        self.lbDate.setGeometry(QtCore.QRect(170, 0, 81, 16))
        self.lbDate.setObjectName("lbDate")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 280, 537, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tabVente = QtWidgets.QTableWidget(self.groupBox_3)
        self.tabVente.setGeometry(QtCore.QRect(20, 20, 521, 236))
        self.tabVente.setRowCount(7)
        self.tabVente.setObjectName("tabVente")
        self.tabVente.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tabVente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabVente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabVente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabVente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabVente.setHorizontalHeaderItem(4, item)
        self.btCancelVt = QtWidgets.QPushButton(self.groupBox_3)
        self.btCancelVt.setGeometry(QtCore.QRect(29, 260, 501, 28))
        self.btCancelVt.setObjectName("btCancelVt")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(590, 360, 181, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lbTotal = QtWidgets.QLabel(self.groupBox_4)
        self.lbTotal.setGeometry(QtCore.QRect(40, 30, 71, 16))
        self.lbTotal.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lbTotal.setObjectName("lbTotal")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(120, 30, 41, 16))
        self.label_11.setObjectName("label_11")
        self.btValider = QtWidgets.QPushButton(self.centralwidget)
        self.btValider.setGeometry(QtCore.QRect(610, 510, 131, 61))
        self.btValider.setObjectName("btValider")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(590, 430, 181, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lbRendu = QtWidgets.QLabel(self.groupBox_5)
        self.lbRendu.setGeometry(QtCore.QRect(40, 30, 71, 16))
        self.lbRendu.setTextFormat(QtCore.Qt.AutoText)
        self.lbRendu.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lbRendu.setObjectName("lbRendu")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(120, 30, 41, 16))
        self.label_12.setObjectName("label_12")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(590, 300, 181, 61))
        self.groupBox_6.setObjectName("groupBox_6")
        self.txCash = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.txCash.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.txCash.setPlainText("")
        self.txCash.setBackgroundVisible(True)
        self.txCash.setObjectName("txCash")
        self.btVisa = QtWidgets.QPushButton(self.groupBox_6)
        self.btVisa.setGeometry(QtCore.QRect(130, 20, 51, 31))
        self.btVisa.setObjectName("btVisa")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btAdd.setDisabled(True)

        #Action
        self.btCheck.clicked.connect(self.check)
        self.btAdd.clicked.connect(self.addArt)
        self.btCancelA.clicked.connect(self.cancelArt)


    def check(self): #verifie si l'article existe
        ref = self.txCode.toPlainText()
        rs = implProduit.check(self,ref)
        if rs:
            self.txCode.setReadOnly(True)
            self.btCheck.setDisabled(True)
            self.btAdd.setDisabled(False)

    def addArt(self):
        tout=0
        ref = self.txCode.toPlainText()
        lib = implProduit.get(self,ref).lib
        pu = implProduit.get(self,ref).pu
        qte = int(self.txQuantite.text())
        tt = pu*qte

        self.code.append(ref)
        self.libelle.append(lib)
        self.prix.append(str(pu))
        self.quantite.append(str(qte))
        self.total.append(str(tt))

        for t in self.total:
            tout = tout + int(t)

        print(self.libelle,self.prix, self.quantite, self.total)
        self.cancelArt()
        self.btAdd.setDisabled(True)
        self.loadData()
        self.lbTotal.setText(str(tout))


    def cancelArt(self): #annuler la saisie de l'article courant
        self.txCode.setPlainText("")
        self.txCode.setReadOnly(False)
        self.txQuantite.setValue(0)
        self.btCheck.setDisabled(False)
        self.btAdd.setDisabled(False)


    def loadData(self): #afficher les elements dans le tableau de ventes
        row0 = 0
        row1=0
        row2=0
        row3=0
        row4=0
        #self.tabVente.setRowCount(len(data))
        for c in self.code:
            self.tabVente.setItem(row0, 0, QTableWidgetItem(c))
            row0 = row0 +1

        for l in self.libelle:
            self.tabVente.setItem(row1, 1, QTableWidgetItem(l))
            row1 = row1 + 1

        for q in self.quantite:
            self.tabVente.setItem(row2, 2, QTableWidgetItem(q))
            row2 = row2 + 1

        for l in self.prix:
            self.tabVente.setItem(row3, 3, QTableWidgetItem(l))
            row3 = row3 + 1

        for l in self.total:
            self.tabVente.setItem(row4, 4, QTableWidgetItem(l))
            row4 = row4 + 1


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Caisse"))
        self.btPrix.setText(_translate("MainWindow", "Prix"))
        self.btStock.setText(_translate("MainWindow", "Stock"))
        self.btCompte.setText(_translate("MainWindow", "Comptes"))
        self.btQuitter.setText(_translate("MainWindow", "Quitter"))
        self.groupBox.setTitle(_translate("MainWindow", "Enregistrer un article"))
        self.btAdd.setText(_translate("MainWindow", "Add"))
        self.btCheck.setText(_translate("MainWindow", "Check"))
        self.label_2.setText(_translate("MainWindow", "Code article"))
        self.label_3.setText(_translate("MainWindow", "Quantité article"))
        self.btCancelA.setText(_translate("MainWindow", "-"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Session"))
        self.label.setText(_translate("MainWindow", "numéro Caisse"))
        self.label_4.setText(_translate("MainWindow", "Caissier"))
        self.label_5.setText(_translate("MainWindow", "Manager"))
        self.lbCaisse.setText(_translate("MainWindow", "-"))
        self.lbCaissier.setText(_translate("MainWindow", "-"))
        self.lbManager.setText(_translate("MainWindow", "-"))
        self.lbDate.setText(_translate("MainWindow", "01/01/2021"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Détail Vente"))
        item = self.tabVente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Code"))
        item = self.tabVente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom Article"))
        item = self.tabVente.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantité"))
        item = self.tabVente.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Prix Unitaire"))
        item = self.tabVente.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total"))
        self.btCancelVt.setText(_translate("MainWindow", "Annuler"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Total Vente"))
        self.lbTotal.setText(_translate("MainWindow", "0 "))
        self.label_11.setText(_translate("MainWindow", "F CFA"))
        self.btValider.setText(_translate("MainWindow", "Valider"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Total à Rendre"))
        self.lbRendu.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "F CFA"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Reglement"))
        self.txCash.setPlaceholderText(_translate("MainWindow", "Total Cash"))
        self.btVisa.setText(_translate("MainWindow", "VISA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
